import { Node } from '@tiptap/core';
import { ParagraphOptions } from '@tiptap/extension-paragraph';
declare const TagNode: Node<any, any>;
declare const DivNode: Node<any, any>;
declare const SectionNode: Node<any, any>;
declare const TheadNode: Node<any, any>;
declare const ParagraphNode: Node<ParagraphOptions, any>;
declare const BrNode: Node<any, any>;
declare const NbspNode: Node<any, any>;
declare const tableExtensions: (Node<import('@tiptap/extension-table').TableOptions, any> | Node<import('@tiptap/extension-table').TableHeaderOptions, any>)[];
export { BrNode, DivNode, NbspNode, ParagraphNode, SectionNode, tableExtensions, TagNode, TheadNode, };
